/**
 * Curated chemistry-only Wikipedia destinations.
 *
 * This is intentionally a small, explicit registry rather than a search
 * index. Adding an entry is a data change: it cannot alter the resolver's
 * matching policy or cause a similarly named cultural/person page to appear.
 */
export type ApprovedWikipediaChemistryPage = {
  key: string;
  pubchemCid: number;
  name: { es: string; en: string };
  wikipedia: { es: string; en: string };
  family: string;
  /** Optional Wikidata id when it is useful to maintain the entry. */
  qid?: string;
  /** Exact, chemistry-only aliases generated by the app's naming layer. */
  aliases: readonly string[];
};

export const WIKIPEDIA_CHEMISTRY_REGISTRY: readonly ApprovedWikipediaChemistryPage[] = [
  {
    key: "methane",
    pubchemCid: 297,
    name: { es: "Metano", en: "Methane" },
    wikipedia: { es: "Metano", en: "Methane" },
    family: "alkane",
    qid: "Q37129",
    aliases: ["metano", "methane"],
  },
  {
    key: "ethane",
    pubchemCid: 6324,
    name: { es: "Etano", en: "Ethane" },
    wikipedia: { es: "Etano", en: "Ethane" },
    family: "alkane",
    aliases: ["etano", "ethane"],
  },
  {
    key: "propane",
    pubchemCid: 6334,
    name: { es: "Propano", en: "Propane" },
    wikipedia: { es: "Propano", en: "Propane" },
    family: "alkane",
    aliases: ["propano", "propane"],
  },
  {
    key: "butane",
    pubchemCid: 7843,
    name: { es: "Butano", en: "Butane" },
    wikipedia: { es: "Butano", en: "Butane" },
    family: "alkane",
    aliases: ["butano", "butane"],
  },
  {
    key: "cyclohexane",
    pubchemCid: 8078,
    name: { es: "Ciclohexano", en: "Cyclohexane" },
    wikipedia: { es: "Ciclohexano", en: "Cyclohexane" },
    family: "cycloalkane",
    aliases: ["ciclohexano", "cyclohexane"],
  },
  {
    key: "benzene",
    pubchemCid: 241,
    name: { es: "Benceno", en: "Benzene" },
    wikipedia: { es: "Benceno", en: "Benzene" },
    family: "arene",
    qid: "Q2270",
    aliases: ["benceno", "benzene"],
  },
  {
    key: "toluene",
    pubchemCid: 1140,
    name: { es: "Tolueno", en: "Toluene" },
    wikipedia: { es: "Tolueno", en: "Toluene" },
    family: "arene",
    aliases: ["tolueno", "toluene", "metilbenceno", "methylbenzene"],
  },
  {
    key: "ethylbenzene",
    pubchemCid: 7500,
    name: { es: "Etilbenceno", en: "Ethylbenzene" },
    wikipedia: { es: "Etilbenceno", en: "Ethylbenzene" },
    family: "arene",
    aliases: ["etilbenceno", "ethylbenzene"],
  },
  {
    key: "methanol",
    pubchemCid: 887,
    name: { es: "Metanol", en: "Methanol" },
    wikipedia: { es: "Metanol", en: "Methanol" },
    family: "alcohol",
    aliases: ["metanol", "methanol"],
  },
  {
    key: "ethanol",
    pubchemCid: 702,
    name: { es: "Etanol", en: "Ethanol" },
    wikipedia: { es: "Etanol", en: "Ethanol" },
    family: "alcohol",
    qid: "Q153",
    aliases: ["etanol", "ethanol", "alcohol etilico", "ethyl alcohol"],
  },
  {
    key: "acetone",
    pubchemCid: 180,
    name: { es: "Acetona", en: "Acetone" },
    wikipedia: { es: "Acetona", en: "Acetone" },
    family: "ketone",
    aliases: ["acetona", "acetone", "propan-2-ona", "propan-2-one"],
  },
  {
    key: "formaldehyde",
    pubchemCid: 712,
    name: { es: "Formaldehído", en: "Formaldehyde" },
    wikipedia: { es: "Formaldehído", en: "Formaldehyde" },
    family: "aldehyde",
    aliases: ["formaldehido", "formaldehyde", "metanal", "methanal"],
  },
  {
    key: "acetaldehyde",
    pubchemCid: 177,
    name: { es: "Acetaldehído", en: "Acetaldehyde" },
    wikipedia: { es: "Acetaldehído", en: "Acetaldehyde" },
    family: "aldehyde",
    aliases: ["acetaldehido", "acetaldehyde", "etanal", "ethanal"],
  },
  {
    key: "acetic-acid",
    pubchemCid: 176,
    name: { es: "Ácido acético", en: "Acetic acid" },
    wikipedia: { es: "Ácido acético", en: "Acetic acid" },
    family: "carboxylic acid",
    aliases: ["acido acetico", "acetic acid", "etanoico", "ethanoic acid"],
  },
  {
    key: "phenol",
    pubchemCid: 996,
    name: { es: "Fenol", en: "Phenol" },
    wikipedia: { es: "Fenol", en: "Phenol" },
    family: "phenol",
    aliases: ["fenol", "phenol"],
  },
  {
    key: "pyridine",
    pubchemCid: 1049,
    name: { es: "Piridina", en: "Pyridine" },
    wikipedia: { es: "Piridina", en: "Pyridine" },
    family: "heterocycle",
    aliases: ["piridina", "pyridine"],
  },
];

function normalizedName(value: string) {
  return value
    .trim()
    .toLocaleLowerCase("es")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ");
}

const byCid = new Map(WIKIPEDIA_CHEMISTRY_REGISTRY.map((entry) => [entry.pubchemCid, entry]));
const byApprovedAlias = new Map(
  WIKIPEDIA_CHEMISTRY_REGISTRY.flatMap((entry) =>
    entry.aliases.map((alias) => [normalizedName(alias), entry] as const),
  ),
);

/**
 * Resolves only an explicitly registered chemistry page. CID is the preferred
 * identity; exact aliases are a conservative offline fallback for a named,
 * app-generated common compound. There is intentionally no search operation.
 */
export function findApprovedWikipediaChemistryPage(input: {
  cid?: number;
  names?: readonly string[];
}) {
  if (Number.isInteger(input.cid) && input.cid) return byCid.get(input.cid);
  for (const name of input.names ?? []) {
    const entry = byApprovedAlias.get(normalizedName(name));
    if (entry) return entry;
  }
  return undefined;
}
